Repository SE701Group2/daily-focus, pull requests merged in 2021-03, with the labels that each got.

#2 adds initialised React app with a suitable file structure
  .gitignore
  README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/components/App/index.js
  client/src/components/App/logo.svg
  client/src/components/App/style.css
  client/src/components/App/test.js
  client/src/index.js
  client/src/reportWebVitals.js
  client/src/setupTests.js
  client/src/style.css
Labels: frontend

#11 moves App to be one level above component
  client/public/logo512.png
  client/public/manifest.json
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.js
  client/src/logo.svg
Labels: refactor

#17 #5 client setup
  .gitattributes
  client/.eslintignore
  client/.eslintrc.json
  client/.prettierignore
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.js
  client/src/reportWebVitals.js
  client/src/setupTests.js
  client/src/style.css
Labels: frontend, setup

#12 Backend init
  server/app.js
  server/bin/www
  server/package-lock.json
  server/package.json
  server/public/stylesheets/style.css
  server/routes/index.js
  server/routes/users.js
  server/views/error.jade
  server/views/index.jade
  server/views/layout.jade
Labels: backend, setup

#30 Add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#21 Adds the material UI icons dependency
  client/package-lock.json
  client/package.json
Labels: frontend, setup

#36 Applied Prettier and ESlint to backend
  .eslintignore
  .eslintrc.json
  .prettierignore
  .prettierrc
  client/.eslintrc.json
  server/app.js
  server/bin/www
  server/public/stylesheets/style.css
  server/routes/index.js
  server/routes/users.js
Labels: backend, setup

#37 Add firebase real-time database to backend server
  package-lock.json
  server/.firebaserc
  server/.gitignore
  server/app.js
  server/database.rules.json
  server/firebase.js
  server/firebase.json
  server/package-lock.json
  server/package.json
Labels: backend, setup

#33 Upload markdown files for issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/setup.md
Labels: documentation, setup

#43 Set up basic todo list API routes
  server/app.js
  server/routes/todo.js
Labels: backend, setup

#34 Add SearchBar component
  client/package-lock.json
  client/src/components/SearchBar/index.js
  client/src/components/SearchBar/style.module.scss
  client/src/components/SearchBar/test.js
Labels: enhancement, frontend

#31 Upload markdown file for pull request template
  .github/pull_request_template.md
Labels: documentation, setup

#47 Added Login API Handler
  package-lock.json
  server/app.js
  server/firebase.json
  server/routes/users.js
  server/validators.js
Labels: backend, enhancement

#62 Rolled back react to react 16 and added enzyme
  client/package-lock.json
  client/package.json
Labels: frontend, setup, testing

#61 added use-persisted-state dependency
  client/package-lock.json
  client/package.json
Labels: frontend

#63 Create select widget modal
  client/src/components/SelectWidgetsModal/SelectWidgetsModal.test.js
  client/src/components/SelectWidgetsModal/index.js
  client/src/components/SelectWidgetsModal/style.module.scss
  client/src/components/WidgetIcon/index.js
  client/src/components/WidgetIcon/style.module.scss
  client/src/components/WidgetIcon/test.js
  client/src/images/calendar.svg
  client/src/images/timer.svg
  client/src/images/toDoList.svg
  client/src/setupTests.js
Labels: enhancement, frontend

#71 Remove port 3000 listener
  server/app.js
Labels: backend, bug

#68 Created method to authenticate users
  server/app.js
  server/auth.js
  server/authorise.test.js
  server/firebase.js
  server/package-lock.json
  server/package.json
  server/routes/todo.js
  server/routes/users.js
  server/test_utils/mocks/mockFirebase.js
Labels: backend, enhancement, testing

#60 Fixed login bug for incorrect credentials
  server/app.js
  server/routes/login.test.js
  server/routes/users.js
  server/test_utils/mocks/mockFirebase.js
  server/validators.js
Labels: backend, bug, testing

#67 Added dateTime component
  client/package-lock.json
  client/src/components/DateTime/DateTime.test.js
  client/src/components/DateTime/index.js
  client/src/components/DateTime/style.module.scss
  client/src/components/Header/index.js
  client/src/components/Header/style.module.scss
Labels: enhancement, frontend

#70 Adds testing for Header and Searchbar component
  client/package-lock.json
  client/package.json
  client/src/App.test.js
  client/src/__snapshots__/App.test.js.snap
  client/src/components/Header/Header.test.js
  client/src/components/Header/__snapshots__/Header.test.js.snap
  client/src/components/SearchBar/SearchBar.test.js
  client/src/components/SearchBar/__snapshots__/SearchBar.test.js.snap
  client/src/components/SearchBar/test.js
Labels: frontend, setup, testing

#72 Create a todo list widget
  client/package-lock.json
  client/package.json
  client/src/components/ToDoList/AddToDo/index.js
  client/src/components/ToDoList/AddToDo/style.module.scss
  client/src/components/ToDoList/ToDoItem/index.js
  client/src/components/ToDoList/ToDoList.test.js
  client/src/components/ToDoList/TodaysToDo/index.js
  client/src/components/ToDoList/UpcomingToDo/index.js
  client/src/components/ToDoList/index.js
  client/src/components/ToDoList/useTodosState.js
Labels: enhancement, frontend

#73 Made a Plant game
  client/package-lock.json
  client/package.json
  client/src/components/PlantButton/PlantTreesModal/ControlButton/index.js
  client/src/components/PlantButton/PlantTreesModal/ControlButton/style.module.scss
  client/src/components/PlantButton/PlantTreesModal/Plant/index.js
  client/src/components/PlantButton/PlantTreesModal/Plant/style.module.scss
  client/src/components/PlantButton/PlantTreesModal/UserFeedback/index.js
  client/src/components/PlantButton/PlantTreesModal/UserFeedback/style.module.scss
  client/src/components/PlantButton/PlantTreesModal/index.js
  client/src/components/PlantButton/PlantTreesModal/style.module.scss
  client/src/components/PlantButton/index.js
  client/src/components/PlantButton/stateUtils.js
  client/src/components/PlantButton/style.module.scss
Labels: enhancement, frontend

#77 #52 - Mock landing page
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/__snapshots__/App.test.js.snap
  client/src/components/LandingPage/LandingPage.test.js
  client/src/components/LandingPage/index.js
  client/src/components/LandingPage/style.module.scss
Labels: enhancement, frontend

#84 Timer Widget
  client/src/components/Timer/index.js
  client/src/components/Timer/style.module.scss
  client/src/components/WidgetIcon/style.module.scss
Labels: enhancement, frontend

#79 To Do List GET Endpoint
  server/routes/tests/get.todo.test.js
  server/routes/todo.js
  server/test_utils/mocks/mockDatabase.js
Labels: backend, enhancement

#85 Add login page with user token retrieval from backend
  client/src/App.js
  client/src/components/LoginPage/LoginPage.test.js
  client/src/components/LoginPage/__snapshots__/LoginPage.test.js.snap
  client/src/components/LoginPage/index.js
  client/src/components/LoginPage/style.module.scss
  client/src/images/focus-logo-w-accent.svg
Labels: enhancement, frontend

#88 #14 create body component
  client/src/App.js
  client/src/__snapshots__/App.test.js.snap
  client/src/components/Body/Body.test.js
  client/src/components/Body/__snapshots__/Body.test.js.snap
  client/src/components/Body/index.js
  client/src/components/Body/style.module.scss
Labels: enhancement, frontend

#86 Connect plant game with the Todo list
  client/package-lock.json
  client/src/components/PlantButton/PlantTreesModal/PlantTreesModal.test.js
  client/src/components/PlantButton/PlantTreesModal/__snapshots__/PlantTreesModal.test.js.snap
  client/src/components/PlantButton/PlantTreesModal/index.js
  client/src/components/PlantButton/index.js
  client/src/components/PlantButton/style.module.scss
  client/src/components/ToDoList/TodaysToDo/index.js
  client/src/components/ToDoList/UpcomingToDo/index.js
  client/src/components/ToDoList/index.js
  client/src/components/ToDoList/useTodosState.js
Labels: enhancement, frontend

#91 Hook up select widgets modal with the local storage of selected widgets. Show widgets.
  client/src/App.js
  client/src/__snapshots__/App.test.js.snap
  client/src/components/Body/index.js
  client/src/components/Header/__snapshots__/Header.test.js.snap
  client/src/components/Header/index.js
  client/src/components/SelectWidgetsModal/WidgetIcon/WidgetIcon.test.js
  client/src/components/SelectWidgetsModal/WidgetIcon/__snapshots__/WidgetIcon.test.js.snap
  client/src/components/SelectWidgetsModal/WidgetIcon/index.js
  client/src/components/SelectWidgetsModal/WidgetIcon/style.module.scss
  client/src/components/SelectWidgetsModal/index.js
  client/src/components/WidgetIcon/test.js
Labels: enhancement, frontend

#78 Add calendar widget component
  client/package-lock.json
  client/package.json
  client/src/components/CalendarWidget/Calendar.scss
  client/src/components/CalendarWidget/EventView/index.js
  client/src/components/CalendarWidget/NewEvent/index.js
  client/src/components/CalendarWidget/index.js
  client/src/components/CalendarWidget/initial-events.js
Labels: enhancement, frontend

#90 Todolist POST Endpoint
  server/package-lock.json
  server/package.json
  server/routes/tests/post.todo.test.js
  server/routes/todo.js
  server/test_utils/mocks/mockDatabase.js
Labels: backend, enhancement, testing

#97 Refactors frontend. Adds tree images to the repo.
  client/src/App.js
  client/src/App.test.js
  client/src/App/App.test.js
  client/src/App/__snapshots__/App.test.js.snap
  client/src/App/index.js
  client/src/App/style.css
  client/src/components/PlantButton/PlantTreesModal/__snapshots__/PlantTreesModal.test.js.snap
  client/src/components/PlantButton/stateUtils.js
  client/src/images/tree0.png
  client/src/images/tree1.png
  client/src/images/tree2.png
  client/src/images/tree3.png
  client/src/images/wateringCan.png
  client/src/pages/HomePage/index.js
  client/src/pages/LandingPage/LandingPage.test.js
  client/src/pages/LandingPage/index.js
  client/src/pages/LandingPage/style.module.scss
  client/src/pages/LoginPage/LoginPage.test.js
  client/src/pages/LoginPage/__snapshots__/LoginPage.test.js.snap
  client/src/pages/LoginPage/index.js
  client/src/pages/LoginPage/style.module.scss
Labels: frontend, refactor

#99 Client README file
  client/README.md
Labels: documentation, frontend

#89 Todolist PUT Endpoint
  server/routes/putTodo.test.js
  server/routes/todo.js
  server/test_utils/mocks/mockDatabase.js
Labels: backend, enhancement, testing

#87 Create DELETE API handler for Todo list (#41)
  server/routes/tests/delete.todo.test.js
  server/routes/todo.js
  server/test_utils/mocks/mockDatabase.js
Labels: backend, enhancement

#101 Server readme
  README.md
  server/README.md
Labels: backend, documentation

#102 Clean up repo
  client/package-lock.json
  client/public/favicon.ico
  client/public/focus-icon.svg
  client/public/index.html
  client/public/logo192.png
  client/public/manifest.json
  client/src/index.js
  client/src/reportWebVitals.js
  package-lock.json
Labels: frontend, refactor

#103 Restructure files in backend
  server/app.js
  server/bin/www
  server/mocks/mockDatabase.js
  server/mocks/mockFirebase.js
  server/package-lock.json
  server/routes/login.js
  server/routes/signup.js
  server/routes/todo.js
  server/tests/app.test.js
  server/tests/authorise.test.js
  server/tests/delete.todo.test.js
  server/tests/get.todo.test.js
  server/tests/login.test.js
  server/tests/post.todo.test.js
  server/tests/put.todo.test.js
  server/tests/signup.test.js
  server/utils/auth.js
  server/utils/date-helper.js
Labels: backend, refactor
