Repository SE701Group2/daily-focus, pull requests merged in 2021-04, with the labels that each got.

#112 Spotify widget
  client/package.json
  client/src/components/Body/index.js
  client/src/components/SelectWidgetsModal/index.js
  client/src/components/SpotifyWidget/SpotifyWidget.test.js
  client/src/components/SpotifyWidget/__snapshots__/SpotifyWidget.test.js.snap
  client/src/components/SpotifyWidget/index.js
  client/src/components/SpotifyWidget/spotify.js
  client/src/components/SpotifyWidget/style.module.scss
  client/src/images/spotify.svg
Labels: enhancement, frontend, testing

#118 Add logic for reseting the plant game.
  client/src/components/PlantButton/PlantTreesModal/ResetButton/index.js
  client/src/components/PlantButton/PlantTreesModal/ResetButton/style.module.scss
  client/src/components/PlantButton/PlantTreesModal/index.js
  client/src/components/PlantButton/stateUtils.js
  client/src/images/reload.png
Labels: enhancement, frontend

#115 FactOfTheDay Widget
  client/src/components/Body/index.js
  client/src/components/FactOfTheDay/FactOfTheDay.test.js
  client/src/components/FactOfTheDay/FactOfTheDayService.js
  client/src/components/FactOfTheDay/__snapshots__/FactOfTheDay.test.js.snap
  client/src/components/FactOfTheDay/index.js
  client/src/components/FactOfTheDay/style.module.scss
  client/src/components/SelectWidgetsModal/index.js
  client/src/images/factOfTheDay.svg
Labels: enhancement, frontend, testing

#119 News widget
  client/src/components/Body/index.js
  client/src/components/NewsWidget/ArticleItem.js
  client/src/components/NewsWidget/NewsWidget.test.js
  client/src/components/NewsWidget/__snapshots__/NewsWidget.test.js.snap
  client/src/components/NewsWidget/index.js
  client/src/components/NewsWidget/newsAPI.js
  client/src/components/NewsWidget/style.module.scss
  client/src/components/SelectWidgetsModal/index.js
  client/src/images/news-widget.svg
Labels: enhancement, frontend

#123 Fact of the day - text overflow bug fixed
  client/src/components/FactOfTheDay/style.module.scss
  client/src/components/SelectWidgetsModal/index.js
Labels: bug, frontend

#124 Weather widget
  client/package-lock.json
  client/package.json
  client/src/components/Body/index.js
  client/src/components/PlantButton/PlantTreesModal/ControlButton/style.module.scss
  client/src/components/PlantButton/PlantTreesModal/Plant/style.module.scss
  client/src/components/PlantButton/PlantTreesModal/UserFeedback/style.module.scss
  client/src/components/SelectWidgetsModal/index.js
  client/src/components/SelectWidgetsModal/style.module.scss
  client/src/components/ToDoList/ToDoItem/index.js
  client/src/components/ToDoList/ToDoList.test.js
  client/src/components/Weather/DayCard/index.js
  client/src/components/Weather/DayCard/style.module.scss
  client/src/components/Weather/HourCard/index.js
  client/src/components/Weather/HourCard/style.module.scss
  client/src/components/Weather/Icon/index.js
  client/src/components/Weather/Icon/style.module.scss
  client/src/components/Weather/Weather.test.js
  client/src/components/Weather/WeatherService.js
  client/src/components/Weather/WeatherService.test.js
  client/src/components/Weather/__snapshots__/Weather.test.js.snap
  client/src/components/Weather/index.js
  client/src/components/Weather/style.module.scss
  client/src/images/weather.svg
Labels: enhancement, frontend, testing

#127 NewsWidget test
  client/src/components/NewsWidget/NewsWidget.test.js
Labels: bug, frontend

#134 Private routing, linked "Sign Up" button to endpoint, data validation for Login and Signup
  client/package-lock.json
  client/package.json
  client/src/App/App.test.js
  client/src/App/__snapshots__/App.test.js.snap
  client/src/App/index.js
  client/src/components/Auth/Auth.js
  client/src/components/PrivateRoute.js
  client/src/pages/LandingPage/index.js
  client/src/pages/LoginPage/index.js
  server/app.js
  server/package-lock.json
  server/package.json
  server/routes/login.js
  server/routes/signup.js
  server/routes/verifyToken.js
  server/tests/login.test.js
  server/tests/signup.test.js
Labels: backend, frontend
